[package]
name = "exa"
version = "0.4.0"
authors = [ "ogham@bsago.me" ]

[[bin]]
name = "exa"
path = "src/bin/main.rs"

[lib]
name = "exa"
path = "src/exa.rs"

[dependencies]
ansi_term = "0.7.1"
bitflags = "0.1"
datetime = "0.4.3"
getopts = "0.2.14"
lazy_static = "0.1.*"
libc = "0.2.9"
locale = "0.2.1"
natord = "1.0.7"
num_cpus = "0.2.7"
number_prefix = "0.2.3"
scoped_threadpool = "0.1.*"
term_grid = "0.1.2"
unicode-width = "0.1.3"
users = "0.5.1"

[features]
default = [ "git" ]
git = [ "git2" ]

[profile.release]
opt-level = 3
debug = false
lto = true

[dependencies.git2]
version = "0.3.2"
optional = true

[dependencies.zoneinfo_compiled]
git = "https://github.com/rust-datetime/zoneinfo-compiled.git"
