[package]
name = "exa"
version = "0.9.0-pre"
authors = [ "ogham@bsago.me" ]
build = "build.rs"

description = "A modern replacement for ls"
homepage = "https://the.exa.website/"
repository = "https://github.com/ogham/exa"
documentation = "https://github.com/ogham/exa"

readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["ls", "files", "command-line"]
license = "MIT"
exclude = ["/devtools/*", "/Makefile", "/Vagrantfile", "/screenshots.png"]


[[bin]]
name = "exa"
path = "src/bin/main.rs"
doc = false


[lib]
name = "exa"
path = "src/exa.rs"

[dependencies]
ansi_term = "0.11"
datetime = "0.4.7"
env_logger = "0.5"
glob = "0.2"
lazy_static = "1"
libc = "0.2.9"
locale = "0.2.1"
log = "0.4"
natord = "1.0.7"
num_cpus = "1.3.0"
number_prefix = "0.2.3"
scoped_threadpool = "0.1.*"
term_grid = "0.1.6"
term_size = "0.3.0"
unicode-width = "0.1.4"
users = "0.8"
zoneinfo_compiled = "0.4.7"

[build-dependencies]
datetime = "0.4.7"

[features]
default = [ "git" ]
git = [ "git2" ]
vendored-openssl = ["git2/vendored-openssl"]

[profile.release]
opt-level = 3
debug = false
lto = true
panic = "abort"

[dependencies.git2]
version = "0.8"
optional = true
default-features = false
